name: Manual-build  # When pushing to any branch then run this action
# Env variable
env:
  DESCRIPTION: "smtp-to-telegram relay"
  ALPINE_VERSION: 3.20

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
  schedule:
    - cron: "0 0 * * 0"

jobs: # job name 
  build-deploy: 
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)     
    steps:
      - name: Check out my repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'lunux/amd64,linux/arm64,linux/arm/v7'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: 'lunux/amd64,linux/arm64,linux/arm/v7'
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image # push The image to the docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ vars.REPO_NAME }}:latest
          labels: |
            MAINTAINER="Marcello Percoco <114474556+MarcelloPercoco@users.noreply.github.com>"
            org.opencontainers.image.source=https://github.com/MarcelloPercoco/smtp_to_telegram
            org.opencontainers.image.description=${{ env.DESCRIPTION }}
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          platforms: |
            linux/arm/v7
            linux/arm64
            linux/amd64
          push: true
          sbom: true
          provenance: mode=max
          annotations: org.opencontainers.image.description=${{ env.DESCRIPTION }}